export const PETITION_CATEGORIES = [
  'Edukacja',
  'Zdrowie',
  'Środowisko',
  'Transport',
  'Infrastruktura',
  'Bezpieczeństwo',
  'Prawa człowieka',
  'Prawa zwierząt',
  'Rynek pracy',
  'Podatki',
  'Mieszkalnictwo',
  'Kultura',
  'Sport',
  'Polityka społeczna',
  'Cyfryzacja',
  'Prawo i sądownictwo',
  'Samorząd lokalny',
  'Gospodarka',
  'Nauka',
  'Energetyka',
  'Inne',
];
